=== GaoNeng-wWw/nuxt-air/content/introduction.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "profile": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "avatar": {
          "type": "string"
        },
        "summary": {
          "anyOf": [
            {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "const": "random"
                },
                "choices": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              },
              "required": [
                "type",
                "choices"
              ],
              "additionalProperties": false
            },
            {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "const": "static"
                },
                "content": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              },
              "required": [
                "type",
                "content"
              ],
              "additionalProperties": false
            }
          ]
        },
        "description": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "name",
        "avatar"
      ],
      "additionalProperties": false
    },
    "social": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "icon": {
            "type": "string"
          },
          "link": {
            "type": "string"
          }
        },
        "required": [
          "icon",
          "link"
        ],
        "additionalProperties": false
      }
    },
    "projects": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "icon": {
            "type": "string"
          },
          "link": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        },
        "required": [
          "icon"
        ],
        "additionalProperties": false
      }
    },
    "organization": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "icon": {
            "type": "string"
          },
          "link": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        },
        "required": [
          "icon"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "profile"
  ],
  "additionalProperties": false
}

=== GaoNeng-wWw/nuxt-air/content/introduction.json
{
  "$schema": "./introduction.schema.json",
  "profile": {
    "name": "GaoNeng-wWw",
    "avatar": "https://avatars.githubusercontent.com/u/31283122?v=4",
    "summary": {
      "type": "random",
      "choices": [
        "我并非全知全能,我只是刚好知道",
        "万物皆奇迹，乃至黑暗与寂静"
      ]
    }
  },
  "projects": [
    {
      "icon": "https://avatars.githubusercontent.com/u/108050589?s=48&v=4",
      "name": "TinyVue",
      "link": "https://github.com/opentiny/tiny-vue"
    },
    {
      "icon": "https://avatars.githubusercontent.com/u/108050589?s=48&v=4",
      "name": "TinyPro",
      "link": "https://github.com/opentiny/tiny-pro"
    },
    {
      "icon": "https://avatars.githubusercontent.com/u/41804496?s=48&v=4",
      "name": "Hello-CTF",
      "link": "https://github.com/ProbiusOfficial/Hello-CTF"
    },
    {
      "icon": "https://avatars.githubusercontent.com/u/123234039?s=48&v=4",
      "name": "klpbbs-survey"
    }
  ],
  "organization": [
    {
      "icon": "https://avatars.githubusercontent.com/u/108050589?s=200&v=4",
      "name": "OpenTiny",
      "link": "https://github.com/opentiny"
    },
    {
      "icon": "https://avatars.githubusercontent.com/u/123234039?s=200&v=4",
      "name": "TeamVastsea",
      "link": "https://github.com/TeamVastsea"
    },
    {
      "icon": "https://avatars.githubusercontent.com/u/213263691?s=200&v=4",
      "name": "klpbbs"
    }
  ],
  "social": [
    {
      "icon": "github",
      "link": "https://github.com/GaoNeng-wWw"
    }
  ]
}
